### ISSUE TITLE
Uncaught TypeError: path must be a string

### ISSUE THREAD

**Issue by brekk** [lysyi3m/atom-postcss-sorting#1]
[Enter steps to reproduce below:]

1. Create a new file with nothing in it.
2. Wait for atom-postcss-sorting to throw error.

**Atom Version**: 1.4.0-beta3
**System**: Mac OS X 10.10.4
**Thrown From**: [postcss-sorting](https://github.com/lysyi3m/atom-postcss-sorting) package, v2.1.2

### Stack Trace

Uncaught TypeError: path must be a string

```
At fs.js:549

TypeError: path must be a string
    at TypeError (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:137:20)
    at Object.fs.readFileSync (fs.js:397:15)
    at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:385:29)
    at Object.module.exports.sort (/Users/bbockrath/.atom/packages/postcss-sorting/lib/postcss-sorting.coffee:41:59)
    at atom-text-editor.<anonymous> (/Users/bbockrath/.atom/packages/postcss-sorting/lib/postcss-sorting.coffee:20:8)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom Beta.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:536:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:359:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
  4x -1:05.7.0 core:close (div.package-detail.panels-item)
     -0:34.7.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.is-focused)
     -0:33.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:32.3.0 pane:split-right (atom-text-editor.editor.is-focused)
     -0:30.6.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.is-focused)
     -0:28.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
 21x -0:24.9.0 core:select-down (atom-text-editor.editor.is-focused)
     -0:20 core:copy (atom-text-editor.editor.is-focused)
     -0:16.1.0 application:new-file (atom-text-editor.editor.is-focused)
     -0:14.9.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:14.2.0 postcss-sorting:run (atom-text-editor.editor.is-focused)
     -0:12 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "spell-check",
      "symbols-view",
      "linter-xo",
      "autosave"
    ]
  }
}
```

### Installed Packages

```coffee
# User
Stylus, v1.2.1
Sublime-Style-Column-Selection, v1.3.0
atom-jade, v0.3.0
atom-react-preview, v1.2.1
auto-detect-indentation, v0.4.2
auto-indent, v0.5.0
autocomplete-paths, v1.0.2
jsonlint, v1.1.2
language-gitignore, v0.2.0
language-gradle, v0.0.3
language-postcss, v1.1.1
language-stylus, v0.2.0
linter, v1.11.3
linter-eslint, v5.2.7
linter-jade, v0.3.2
linter-jsonlint, v1.1.2
linter-stylint, v2.0.1
minimap, v4.19.0
package-manager-commands, v2.0.3
pigments, v0.19.5
postcss-sorting, v2.1.2
pretty-json, v0.4.1
project-manager, v2.6.5
project-view, v0.4.1
set-syntax, v0.3.0
tag, v0.3.0

# Dev
No dev packages
```

**Comment by brekk** [comment]
My mistake, I was hitting a keymap Cmd + Shift + S in an empty file.
